version: 0.0
os: linux
format: ECS
files:
  - source: php/index.php
    destination: /var/www/php/

hooks:
  AfterInstall:
    - location: scripts/install_dependencies.sh
      timeout: 1000
      runas: root
  ApplicationStart:
    - location: scripts/start_server.sh
      timeout: 1000
      runas: root
  ApplicationStop:
    - location: scripts/stop_server.sh
      timeout: 1000
      runas: root
