version: '3.8'

services:
  # MySQL database
  mysql:
    image: mysql:8.0.28
    container_name: raneemsql
    environment:
      MYSQL_DATABASE: 'super-app'
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql

  # Node.js application
  node-app:
    image: ramenib/superappnode:59-b53eec8699bb273bf2ab6e7d4d825dc5330a2d31
    container_name: raneemnode
    depends_on:
      - mysql
    ports:
      - "3000:3000"
    environment:
      MYSQL_HOST: mysql
      MYSQL_DATABASE: 'super-app'
      MYSQL_USER: 'root'
      MYSQL_PASSWORD: 'password'

  # PHP application
  php-app:
    image: ramenib/superappphp:80-b68dc67ea87a061ec8e4b6ae9c435cd1af8d079c
    container_name: raneemphp
    depends_on:
      - mysql
    ports:
      - "80:80"
    environment:
      MYSQL_HOST: mysql 
      MYSQL_DATABASE: 'super-app'
      MYSQL_USER: 'root' 
      MYSQL_PASSWORD: 'password'

volumes:
  mysql-data:  # Volume for persistent MySQL data
