version: '3.8'

services:
   #MySQL database
  mysql:
    image: mysql:8.0.28
    container_name: raneemsql
    environment:
      MYSQL_DATABASE: 'super-app'
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql

  # Node.js application
  node-app:
    image: ramenib/sanode:1.0
    container_name: raneemnode
    depends_on:
      - mysql
    ports:
      - "3000:3000"
    environment:
      MYSQL_HOST: mysql
      MYSQL_DATABASE: 'super-app'
      MYSQL_USER: 'root'
      MYSQL_PASSWORD: 'password'

  # PHP application
  php-app:
    image: ramenib/saphp:1.0
    container_name: raneemphp
    depends_on:
      - mysql
    ports:
      - "80:80"
    environment:
      MYSQL_HOST: mysql 
      MYSQL_DATABASE: 'super-app'
      MYSQL_USER: 'root' 
      MYSQL_PASSWORD: 'password'

volumes:
  mysql-data:  # Volume for persistent MySQL data
