version: '3.8'  # Specify the Docker Compose version

services:
  - php-app:
    # Image to use for the service
    image: ramenib/superappphp:80-b68dc67ea87a061ec8e4b6ae9c435cd1af8d079c

  - node-app:
    image: ramenib/superappnode:59-b53eec8699bb273bf2ab6e7d4d825dc5330a2d31

ports:
  # Define exposed ports for your services
  - "80:80"  # Maps container port 80 (PHP) to host port 80
