name: Docker Build and Push

on:
  workflow_dispatch:
  
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest 
    strategy:
      matrix:
        # Definining configurations for each Dockerfile
        build_config:
          - name: image1  
            dockerfile: ./node/Dockerfile  # Path to Dockerfile 1 (relative to root)
          - name: image2  
            dockerfile: ./php/Dockerfile  # Path to Dockerfile 2 (relative to root)
    steps:
      - uses: actions/checkout@v3  # Checkout code from the repository
      - name: Login to Docker Hub
        uses: docker/login-action@v2  # Login to Docker Hub using secrets
        with:
          username: ${{ secrets.DOCKERUSER }}
          password: ${{ secrets.DOCKERPASS }}
      - name: Build and push Docker image
        run: |
          docker build -t <username>/${{ matrix.build_config.name }}:<tag> ${{ matrix.build_config.dockerfile }}
          docker push <username>/${{ matrix.build_config.name }}:<tag>
        
