name: Docker Image1 CI

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
    
jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: checkout code
      uses: actions/checkout@v4
      
    - name: Build the Docker phpimage
      run: docker build -f ./php/Dockerfile --tag superappnode:${{ github.run_number }}-${{github.sha}} .


  #  - name: checkout codepush docker image to registry
  #  - run:  docker push ramenib/superappnode
