name: Docker Image CI

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
    
jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: checkout code
      uses: actions/checkout@v4
      
    - name: Build the Docker nodeimage
      run: docker build -f './node/Dockerfile' --tag my-image-name:${{ github.run_number }}-${{ github.sha }}
