name: Docker Image2 CI

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
    
jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: checkout code
      uses: actions/checkout@v4
      #with:
        #path: node 

    - name: Build the Docker nodeimage
      run: docker build -f ./node/Dockerfile --tag ramenib/sanode:${{ github.run_number }} ./node
    
    - name: Login to Docker Hub
      run:  docker login -u ${{  secrets.DOCKERUSER  }} -p ${{  secrets.DOCKERPASS  }}

  
    - name: checkout codepush docker image to registry
      run:  docker push ramenib/sanode:${{ github.run_number }}
