name: Docker Image1 CI

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
    
jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: checkout code
      uses: actions/checkout@v4
      
    - name: Build the Docker phpimage
      run: docker build -f ./php/Dockerfile --tag ramenib/saphp:${{ github.run_number }} .


    - name: Login to Docker Hub
      run:  docker login -u ${{  secrets.DOCKERUSER  }} -p ${{  secrets.DOCKERPASS  }}

    - name: checkout codepush docker image to registry
      run:  docker push ramenib/saphp:${{ github.run_number }}
